# Generated by Django 4.2.7 on 2023-11-30 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terraforming_mars_vp_calc_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terraforming_mars_vp_calc_app.person'),
        ),
    ]
