# Generated by Django 4.2.7 on 2023-11-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terraforming_mars_vp_calc_app', '0002_person_alter_player_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player',
            new_name='Score',
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.TextField(max_length=200, unique=True),
        ),
    ]
