# Generated by Django 4.2.7 on 2023-11-30 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terraforming_mars_vp_calc_app', '0003_rename_player_score_alter_person_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='name',
            new_name='person',
        ),
        migrations.RemoveField(
            model_name='score',
            name='was_winner',
        ),
    ]
